### ISSUE TITLE
new Sensors ID>65000

### ISSUE THREAD

**Issue by frettijule** [redflo/pylarexx#2]
What do yo need to include reading sensors with ids over 65000?
in the original c-program from martin mares that is included: https://mj.ucw.cz/sw/arexxd/

I can't send you my BS-510 but logfiles etc., but how can i got them?

**Comment by redflo** [comment]
I will check the changes in the sources of Martin Mares tonight. If it is easy, you can then check if it works.

**Comment by redflo** [comment]
I committed a change in Logger.py. Can you check, if your sensors get detected now?

**Comment by frettijule** [comment]
It seems doesn't work!
The same sensor works under martin's C-program.

**Comment by redflo** [comment]
Can you start pylarexx with -vvv to get debugging output? If you use systemd, change the ExecStart line and add -vvv. Or you change the pylarexx.py line 82 to "verbose = 3" and restart pylarexx.
Send me some debugging lines that contain the raw data. Looks like this:
`array('B', [0, 10, 154, 68, 22, 214, 105, 207, 250, 37, 49, 0, 255, 36, 10, 215, 87, 207, 250, 37, 35, 10, 216, 79, 24, 122, 88, 207, 250, 37, 39, 0, 109, 65, 5, 106, 169, 205, 250, 37, 45, 0, 108, 65, 24, 198, 152, 199, 250, 37, 43, 0, 93, 255, 255, 255, 255, 255, 71, 155, 68, 200, 120, 251])
`

**Comment by frettijule** [comment]
[log.log](https://github.com/redflo/pylarexx/files/4330129/log.log)
Here is a little log-file. I hope, it helps

**Comment by redflo** [comment]
Can you also give me the IDs and types of the sensors that do not work?

**Comment by redflo** [comment]
Can you make a full update and check again. It will probably work now. Keep DetectUnknownSensors to yes.

**Comment by frettijule** [comment]
With the new version, i got an error on start:
/usr/local/pylarexx/pylarexx.py -v -f /etc/pylarexx.yml
Traceback (most recent call last):
  File "/usr/local/pylarexx/pylarexx.py", line 129, in <module>
    sys.exit(main())
  File "/usr/local/pylarexx/pylarexx.py", line 105, in main
    myDataLogger = datalogger.Logger.TLX00(params)
  File "/usr/local/pylarexx/datalogger/Logger.py", line 39, in __init__
    self.readConfigFile(params['conffile'])
  File "/usr/local/pylarexx/datalogger/Logger.py", line 46, in readConfigFile
    self.config=yaml.full_load(content)
AttributeError: module 'yaml' has no attribute 'full_load'


I can only test at work, because there is the receiver!

**Comment by redflo** [comment]
Reverted one change, can you pull the changes and try again?

**Comment by frettijule** [comment]
there is still an error
Here the  output and the log-file
[arexx.out.txt](https://github.com/redflo/pylarexx/files/4337505/arexx.out.txt)

[log.log](https://github.com/redflo/pylarexx/files/4337504/log.log)
My sensors have the ids: 137131, 134241 and 12052
The 12052 is an TL-3TSN, the others are TSN-EXT44

**Comment by redflo** [comment]
Can you try again? From the logs is can see the sensors, but sensors with high ID have a internal id and a display id. I changed all Listeners to dump the written id and not the internal.

**Comment by redflo** [comment]
Did some rework. I think, this is fixed now. Please try. Re-open this issue, if it is still broken.
